<?php

/**
 * @file
 * Custom module file for tfs.
 */

function tfs_custom_init(){
}

/**
 * Implements hook_menu().
 */
function tfs_custom_menu() {
  $items = array();

  $items['rebecca/new/confirm-attendance/%tfs_custom_user_tfs'] = array(
    'title' => 'Confirm attendance',
    'description' => 'Accept or decline invitation',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tfs_custom_confirm_attendance', 3),
    'access callback' => 'tfs_custom_confirm_attendance_access',
    'access arguments' => array(3),
    'file' => 'tfs_custom.pages.inc',
  );

  $items['admin/config/emails'] = array(
    'title' => 'Ticket4Show Emails',
    'description' => 'Ticket 4 show emails',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tfs_custom_email_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'tfs_custom.emails.inc',
  );

  return $items;

}

/**
 * Menu autoloader.
 *
 * @param string $uid
 *   The uid of the user
 */
function tfs_custom_user_tfs_load($uid){
  $user_account = &drupal_static(__FUNCTION__, NULL);

  if (empty($user_account)) {
    $user_account = user_load($uid);
  }
  return $user_account;
}

function tfs_custom_confirm_attendance_access($user_account){
  global $user;
  $args = arg();

  if (!user_is_logged_in()){
    drupal_goto('user/login', array('query' => array('destination' => "rebecca/new/confirm-attendance/$user_account->uid")));
  }

  if ($user->uid == $args[3] || $user->uid == 1) {
    return TRUE;
  }

  return FALSE;
}

/**
 * @see hook_mail
 */
function tfs_custom_mail($key, &$message, $params) {
  global $base_url;
  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
  switch ($key) {
    case 'send_rebecca_confirmation_email':
      $confirmation_body = variable_get('tfs_custom_ask_confirm_body', array(
        'value' => '',
        'format' => '',
      ));

      $message['subject'] = variable_get('tfs_custom_ask_confirm_subject');
      $message['body'][] = t($confirmation_body['value'], array(
        '!uid' => $params['uid'],
        '!CUSTOM_CONFIRM_LINK' => $params['CUSTOM_CONFIRM_LINK'],
      ));
      break;
    case 'rebecca_confirmation_yes':
      $message['subject'] = t('E-Ticket to REBECCA London premiere attached');
      $message['body'][] .= t('Hi !fname, <br> <br>Please come with your e-ticket on the night to grant you access to watch the film.', array(
        '!fname' => $params['fname']
      ));
      $message['body'][] .= t("<img src='$base_url/sites/all/themes/eventus/images/E-Ticket_invite_1.jpg'>");
      break;
  }
}
