<?php

/**
 * @file
 * Custom module file for tfs.
 */

function tfs_custom_init(){
}

/**
 * Implements hook_menu().
 */
function tfs_custom_menu() {
  $items = array();

  $items['rebecca/new/confirm-attendance/%tfs_custom_user_tfs'] = array(
    'title' => 'Confirm attendance',
    'description' => 'Accept or decline invitation',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tfs_custom_confirm_attendance', 3),
    'access callback' => 'tfs_custom_confirm_attendance_access',
    'access arguments' => array(3),
    'file' => 'tfs_custom.pages.inc',
  );

  $items['admin/config/emails'] = array(
    'title' => 'Ticket4Show Emails',
    'description' => 'Ticket 4 show emails',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tfs_custom_email_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'tfs_custom.emails.inc',
  );

  return $items;

}

/**
 * Menu autoloader.
 *
 * @param string $uid
 *   The uid of the user
 */
function tfs_custom_user_tfs_load($uid){
  $user_account = &drupal_static(__FUNCTION__, NULL);

  if (empty($user_account)) {
    $user_account = user_load($uid);
  }
  return $user_account;
}

function tfs_custom_confirm_attendance_access($user_account){
  global $user;
  $args = arg();

  if (!user_is_logged_in()){
    drupal_goto('user/login', array('query' => array('destination' => "rebecca/new/confirm-attendance/$user_account->uid")));
  }

  if ($user->uid == $args[3] || $user->uid == 1) {
    return TRUE;
  }

  return FALSE;
}

/**
 * @see hook_mail
 */
function tfs_custom_mail($key, &$message, $params) {
  global $base_url;
  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
  switch ($key) {
    case 'send_rebecca_confirmation_email':
      $confirmation_body = variable_get('tfs_custom_ask_confirm_body', array(
        'value' => '',
        'format' => '',
      ));

      $message['subject'] = variable_get('tfs_custom_ask_confirm_subject');
      $message['body'][] = t($confirmation_body['value'], array(
        '!uid' => $params['uid'],
        '!CUSTOM_CONFIRM_LINK' => $params['CUSTOM_CONFIRM_LINK'],
      ));
      break;
    case 'basket_mouth':
      $name = $params['first_name'];
      $message['Subject'] = 'Your chance to WIN tickets to see Basketmouth LIVE!';
      $content = '';
      $content .= "<img src='http://ticket4show.com/sites/default/files/Basketmouth_14FEB2017_Flyer_Front-header.jpg'>";
      $content .= "Dear $name,";
      $content .= "<br>";
      $content .= "We are giving away free tickets to <strong>Basketmouth live @ The SSE Area </strong> on 14th February 2017.";
      $content .= "<br>";
      $content .= "Please click <a href='http://ticket4show.com/basket-mouth-valentines'> here</a> to enter the competition.";
      $content .= "<br>";
      $content .= "Best of luck,";
      $content .= "<em>Staff at Ticket4Show.com</em>";
      $message['Body'] = $content;
      break;
    case 'contact_us':
      $message['subject'] = 'A new Contact Us Submission at Ticket4show.com';
      $message['body'][] = t(
      "
      Name: !name<br>
      Email: !email<br>
      Message: !message<br>
      ", array(
        '!name' => $params['name'],
        '!email' => $params['email'],
        '!message' => $params['message'],
      ));
      break;
    case 'rebecca_confirmation_yes':
      $message['subject'] = t('E-Ticket to REBECCA London premiere attached');
      $message['body'][] .= t('Hi !fname, <br> <br>Please come with your e-ticket on the night to grant you access to watch the film.', array(
        '!fname' => $params['fname']
      ));
      $message['body'][] .= t("<img src='$base_url/sites/all/themes/eventus/images/E-Ticket_invite_1.jpg'>");
      break;
    case 'thank_you':
      $message['subject'] = t('REBECCA London premiere - Thank you');
      $message['body'][] .= t('Dear @name,
<br><br>
On behalf of Evrit films and Ticket4show, I would like to take this opportunity to express my sincere appreciation to you for coming out on Friday, the 22nd January 2016 to support Shirley F Manso’s film ‘REBECCA’ exclusive London red carpet at Odeon Greenwich cinema.
<br><br>
I hope you had a fantastic time at the event and a smooth journey back home. I look forward seeing you again at our next event which will be announced very soon.
<br><br>
Please see published photos of the event by www.ghanacelebrities.com
<br><br>
Have a wonderful day
<br><br>
Many thanks,<br><br>
Henry kwao<br><br>
<i>Chief executive officer</i>', array(
        '@name' => $params['name']
      ));
      break;
  }
}

/**
 *
 * @param $entity
 * @param $type
 *
 * @see hook_entity_presave()
 */
function tfs_custom_entity_presave($entity, $type) {

  if ($type == 'entityform' && $entity->type == 'contact_us') {

    $name = $entity->field_name[LANGUAGE_NONE][0]['value'];
    $message = $entity->field_message[LANGUAGE_NONE][0]['value'];
    $email = $entity->field_e_mail['und'][0]['email'];

    $params = array(
      'name' => $name,
      'message' => $message,
      'email' => $email,
    );

    drupal_mail('tfs_custom', 'contact_us', 'info@ticket4show.com', language_default(), $params);
  }
}

function tfs_custom_form_alter(&$form, &$form_state, $form_id) {
  global $user;

  if ($form_id == 'basketmouth_entityform_edit_form') {
    if ($user->uid == 0){
      drupal_set_message(t('You must be logged in or registered first to enter the competition!'));
      drupal_goto('user', array('query' => array('destination' => 'basket-mouth-valentines')));
    }

    $entityform = entityform_load_multiple(array(), array('uid' => $user->uid));
    if (!empty($entityform)) {
      $form['actions']['submit']['#value'] = t('You have already submitted!');
      $form['actions']['submit']['#disabled'] = TRUE;
      $form['field_what_is_basketmouth_s_real']['#disabled'] = TRUE;
    }
  }
}

